import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/main.module.scss";
import Chart from "chart.js";
const inter = Inter({ subsets: ["latin"] });

//Implemented for the stackedBarGraph
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
} from "chart.js";
import { Bar, Doughnut } from "react-chartjs-2";
import { faker } from "@faker-js/faker";

ChartJS.register(
  ArcElement,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

const options = {
  plugins: {
    title: {
      display: true,
      // text: "Carbon Footprint",
    },
    legend: {
      display: false,
    },
  },
  responsive: true,
  scales: {
    x: {
      stacked: true,
      grid: {
        display: false,
      },
    },
    y: {
      stacked: true,
      grid: {
        display: false,
      },
    },
  },
};
const labels = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
];
const data = {
  labels: labels,
  datasets: [
    {
      label: "Data 1",
      data: labels.map(function () {
        return faker.datatype.number({ min: 0, max: 1000 });
      }),
      // data: [100, 200, 300, 400, 500, 600, 700],
      backgroundColor: "#57cc78",
      borderRadius: 10,
    },
    {
      label: "Data 2",
      data: labels.map(function () {
        return faker.datatype.number({ min: 0, max: 1000 });
      }),
      // data: [100, 200, 300, 400, 500, 600, 700],
      backgroundColor: "#55dbdb",
      borderRadius: 10,
    },
    {
      label: "Data 3",
      data: labels.map(function () {
        return faker.datatype.number({ min: 0, max: 1000 });
      }),
      // data: [100, 200, 300, 400, 500, 600, 700],
      backgroundColor: "#e2ff32",
      borderRadius: 10,
    },
    {
      label: "Data 4",
      data: labels.map(function () {
        return faker.datatype.number({ min: 0, max: 1000 });
      }),
      // data: [100, 200, 300, 400, 500, 600, 700],
      backgroundColor: "#fec102",
      borderRadius: 10,
    },
  ],
};

// Implemented for the Doughnut
const options2 = {
  plugins: {
    legend: {
      display: false,
    },
  },
  cutout: 80,
};

const data2 = {
  labels: ["Green", "Sky", "Yellow", "Orange"],
  datasets: [
    {
      label: "# of Votes",
      data: [22, 16, 27, 35],
      backgroundColor: ["#57cc78", "#55dbdb", "#e2ff32", "#fec102"],
      borderColor: ["#57cc78", "#55dbdb", "#e2ff32", "#fec102"],
      borderWidth: 1,
    },
  ],
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div className={styles.container}>
          <div className={styles.leftcontainer}>
            <header className={styles.leftcontainer__header}>
              <div className={styles.leftcontainer__logo__container}>
                <img
                  src="/greenstitch_logo_icon.svg"
                  alt="greenstitch logo"
                  className={styles.leftcontainer__logo}
                />
              </div>
            </header>
            <div className={styles.dashboardcontainer}>
              <h2 className={styles.dashboardcontainer__heading__primary}>
                DASHBOARD
              </h2>
              <div className={styles.dashboardcontainer__item__1}>
                <div
                  className={`${styles.dashboardcontainer__dashboard} ${styles.dashboardcontainer__items}`}
                >
                  <div className={styles.dashboardcontainer__items__left}>
                    <img src="/dashboard_icon.png" alt="dashboard__icon" />
                    <h3
                      className={styles.dashboardcontainer__heading__secondary}
                    >
                      Dashboard
                    </h3>
                  </div>
                  <img
                    src="/dashboard_down_icon.svg"
                    alt="dashboard down icon"
                  />
                </div>
              </div>
              <h2 className={styles.dashboardcontainer__heading__primary}>
                PAGES
              </h2>
              <div className={styles.dashboardcontainer__item__2}>
                <div
                  className={`${styles.dashboardcontainer__helpcenter} ${styles.dashboardcontainer__items}`}
                >
                  <div className={styles.dashboardcontainer__items__left}>
                    <img src="/help_center_icon.svg" alt="dashboard__icon" />
                    <h3
                      className={styles.dashboardcontainer__heading__secondary}
                    >
                      Help Center
                    </h3>
                  </div>
                  <img
                    src="/dashboard_down_icon.svg"
                    alt="dashboard down icon"
                  />
                </div>
                <div
                  className={`${styles.dashboardcontainer__filemanager} ${styles.dashboardcontainer__items}`}
                >
                  <div className={styles.dashboardcontainer__items__left}>
                    <img src="/file_manager_icon.svg" alt="dashboard__icon" />
                    <h3
                      className={styles.dashboardcontainer__heading__secondary}
                    >
                      File Manager
                    </h3>
                  </div>
                  <img
                    src="/dashboard_down_icon.svg"
                    alt="dashboard down icon"
                  />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.rightcontainer}>
            <div className={styles.rightcontainer__nav}>
              <div className={styles.rightcontainer__nav__search__cont}>
                <img
                  src="/search_icon.svg"
                  alt="search_icon"
                  className={styles.rightcontainer__nav__search__cont__img}
                />
                <input
                  type="text"
                  className={styles.rightcontainer__nav__search__cont__input}
                  placeholder="Search..."
                />
              </div>
              <div className={styles.rightcontainer__nav__icons}>
                <img
                  src="/notification_icon.svg"
                  alt="notification icon"
                  className={styles.rightcontainer__nav__icons__icon__1}
                />
                <img
                  src="/calendar_icon.svg"
                  alt="calendar icon"
                  className={styles.rightcontainer__nav__icons__icon__2}
                />
                <img
                  src="/file_manager_icon.svg"
                  alt="file_manager icon"
                  className={styles.rightcontainer__nav__icons__icon__3}
                />
                <img
                  src="/gima_icon.svg"
                  alt="gima_icon"
                  className={styles.rightcontainer__nav__icons__icon__4}
                />
              </div>
            </div>
            <div className={styles.rightcontainer__middlecontainer}>
              <div className={styles.rightcontainer__middlecontainer__1}>
                <div
                  className={styles.rightcontainer__middlecontainer__1__card}
                >
                  <h3
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp3
                    }
                  >
                    Carbon Footprint
                  </h3>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp2
                    }
                  >
                    2,412,314t
                  </h2>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp4
                    }
                  >
                    CO2e
                  </h2>
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__1__card__percent
                    }
                  >
                    <h2>-45%</h2>
                  </div>
                </div>
                <div
                  className={styles.rightcontainer__middlecontainer__1__card}
                >
                  <h3
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp3
                    }
                  >
                    Emission By Spinning
                  </h3>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp2
                    }
                  >
                    72,3694t
                  </h2>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp4
                    }
                  >
                    CO2e
                  </h2>
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__1__card__percent
                    }
                  >
                    <h2>-60%</h2>
                  </div>
                </div>
                <div
                  className={styles.rightcontainer__middlecontainer__1__card}
                >
                  <h3
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp3
                    }
                  >
                    Emission By Transportation
                  </h3>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp2
                    }
                  >
                    361,874t
                  </h2>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp4
                    }
                  >
                    CO2e
                  </h2>
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__1__card__percent
                    }
                  >
                    <h2>0%</h2>
                  </div>
                </div>
                <div
                  className={styles.rightcontainer__middlecontainer__1__card}
                >
                  <h3
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp3
                    }
                  >
                    Emission By Carding
                  </h3>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp2
                    }
                  >
                    241,231
                  </h2>
                  <h2
                    className={
                      styles.rightcontainer__middlecontainer__1__card__hp4
                    }
                  >
                    CO2e
                  </h2>
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__1__card__percent
                    }
                  >
                    <h2>+0.6%</h2>
                  </div>
                </div>
              </div>
              <div className={styles.rightcontainer__middlecontainer__2}>
                <div
                  className={styles.rightcontainer__middlecontainer__2__left}
                >
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__2__left__top
                    }
                  >
                    <h1>Carbon Footprint</h1>
                    <div
                      className={
                        styles.rightcontainer__middlecontainer__2__left__top__bullets
                      }
                    >
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__left__top__bullets__bullet
                        }
                      >
                        <img src="/green_bullet.svg" alt="greenbullet" />
                        <h3>Spinning</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__left__top__bullets__bullet
                        }
                      >
                        <img src="/skyblue_bullet.svg" alt="greenbullet" />
                        <h3>Transportation</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__left__top__bullets__bullet
                        }
                      >
                        <img src="/yellow_bullet.svg" alt="greenbullet" />
                        <h3>Carding</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__left__top__bullets__bullet
                        }
                      >
                        <img src="/orange_bullet.svg" alt="greenbullet" />
                        <h3>Heating & Cooling</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__left__top__bullets__bullet
                        }
                      >
                        <img src="/dashboard_carbon.svg" alt="greenbullet" />
                      </div>
                    </div>
                  </div>
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__2__left__bottom
                    }
                  >
                    <Bar options={options} data={data} />;
                  </div>
                </div>
                <div
                  className={styles.rightcontainer__middlecontainer__2__right}
                >
                  <h1
                    className={
                      styles.rightcontainer__middlecontainer__2__right__heading
                    }
                  >
                    Top emissions by type
                  </h1>
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__2__right__doughnut
                    }
                  >
                    <Doughnut options={options2} data={data2} />
                  </div>
                  <div
                    className={
                      styles.rightcontainer__middlecontainer__2__right__bottom__coldetails
                    }
                  >
                    <div
                      className={
                        styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1
                      }
                    >
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__left
                        }
                      >
                        <img src="/green_bullet.svg" alt="greenbullet" />
                        <h3>Spinning</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__right
                        }
                      >
                        22%
                      </div>
                    </div>
                    <div
                      className={
                        styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1
                      }
                    >
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__left
                        }
                      >
                        <img src="/skyblue_bullet.svg" alt="greenbullet" />
                        <h3>Transportation</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__right
                        }
                      >
                        16%
                      </div>
                    </div>
                    <div
                      className={
                        styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1
                      }
                    >
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__left
                        }
                      >
                        <img src="/yellow_bullet.svg" alt="greenbullet" />
                        <h3>Carding</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__right
                        }
                      >
                        27%
                      </div>
                    </div>
                    <div
                      className={
                        styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1
                      }
                    >
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__left
                        }
                      >
                        <img src="/orange_bullet.svg" alt="greenbullet" />
                        <h3>Heating & Cooling</h3>
                      </div>
                      <div
                        className={
                          styles.rightcontainer__middlecontainer__2__right__bottom__coldetails__1__right
                        }
                      >
                        35%
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
